allowBuilds:
  '@swc/core': true
  cbor-extract: true
  core-js: true
  esbuild: true
  tree-sitter-go: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-typescript: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - '@swc/core'
  - cbor-extract
  - core-js
  - esbuild
  - tree-sitter-go
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-typescript
  - unrs-resolver
  - workerd
